"""fase2 invitations reputation

Revision ID: 593a7261594f
Revises: 138636687e10
Create Date: 2026-06-01 23:37:25.062692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '593a7261594f'
down_revision: Union[str, Sequence[str], None] = '138636687e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workshop_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('workshop_id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', name='invitationstatus'), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['workshop_id'], ['workshops.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('incident_id', 'workshop_id', name='uq_invitation_incident_workshop')
    )
    op.create_index(op.f('ix_workshop_invitations_id'), 'workshop_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_workshop_invitations_incident_id'), 'workshop_invitations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_workshop_invitations_status'), 'workshop_invitations', ['status'], unique=False)
    op.create_index(op.f('ix_workshop_invitations_tenant_id'), 'workshop_invitations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_workshop_invitations_workshop_id'), 'workshop_invitations', ['workshop_id'], unique=False)
    # server_default para no romper filas existentes; el modelo aplica el
    # default a nivel de aplicacion en filas nuevas.
    op.add_column('workshops', sa.Column('reputation_points', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('workshops', sa.Column('invitations_sent', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('workshops', sa.Column('invitations_accepted', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('workshops', sa.Column('invitations_ignored', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('workshops', sa.Column('avg_response_seconds', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'avg_response_seconds')
    op.drop_column('workshops', 'invitations_ignored')
    op.drop_column('workshops', 'invitations_accepted')
    op.drop_column('workshops', 'invitations_sent')
    op.drop_column('workshops', 'reputation_points')
    op.drop_index(op.f('ix_workshop_invitations_workshop_id'), table_name='workshop_invitations')
    op.drop_index(op.f('ix_workshop_invitations_tenant_id'), table_name='workshop_invitations')
    op.drop_index(op.f('ix_workshop_invitations_status'), table_name='workshop_invitations')
    op.drop_index(op.f('ix_workshop_invitations_incident_id'), table_name='workshop_invitations')
    op.drop_index(op.f('ix_workshop_invitations_id'), table_name='workshop_invitations')
    op.drop_table('workshop_invitations')
    # ### end Alembic commands ###
