"""fase7 incident client_uuid

Revision ID: b1767a336625
Revises: 593a7261594f
Create Date: 2026-06-02 01:22:58.331458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1767a336625'
down_revision: Union[str, Sequence[str], None] = '593a7261594f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('client_uuid', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_incidents_client_uuid'), 'incidents', ['client_uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_incidents_client_uuid'), table_name='incidents')
    op.drop_column('incidents', 'client_uuid')
    # ### end Alembic commands ###
